/**
 * @author laura
 */

package br.cesjf.lpiu.interfaces;

import br.cesjf.lpiu.arquivos.ArquivoInCarro;
import br.cesjf.lpiu.arquivos.ArquivoOutCarro;
import br.cesjf.lpiu.modelo.Automovel;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.ImageIcon;
import java.awt.Toolkit;
import java.awt.Dimension;
import java.awt.Insets;
import java.awt.Component;

public class CadCarro extends javax.swing.JFrame {
    
    private ArquivoInCarro arqin = new ArquivoInCarro();
    int linha; //pega a linha que o usuário clicou na tabela - para retornar dados ao formulário
    private ArquivoOutCarro arqout = new ArquivoOutCarro();
    
    public CadCarro() {
    	setIconImage(Toolkit.getDefaultToolkit().getImage(CadCarro.class.getResource("/br/cesjf/lpiu/icons/logo2.png")));
        initComponents();
        auto = new Automovel();
        try {
            arqout.abrir();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CadCarro.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(CadCarro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public Automovel auto = null;
    
    public void limpar() {
        txtPlaca.setText("");
        txtModelo.setText("");
        txtData.setText("");
        txtValorBasico.setText("");
        comboMotorizacao.setSelectedIndex(-1);
        txtAliquota.setText("");
        txtImposto.setText("");
        txtValorBasico.setText("");
        txtValorTotal.setText("");
        btTipoCarro.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btTipoCarro = new javax.swing.ButtonGroup();
        btLimpar = new javax.swing.JButton();
        btLimpar.setIcon(new ImageIcon(CadCarro.class.getResource("/br/cesjf/lpiu/icons/limpar.png")));
        rbCarga = new javax.swing.JRadioButton();
        lblPlaca = new javax.swing.JLabel();
        txtValorTotal = new javax.swing.JTextField();
        lblDadosAutomovel = new javax.swing.JLabel();
        comboMotorizacao = new javax.swing.JComboBox<>();
        jbAdd = new javax.swing.JButton();
        jbAdd.setIcon(new ImageIcon(CadCarro.class.getResource("/br/cesjf/lpiu/icons/add.png")));
        lblAno = new javax.swing.JLabel();
        txtAliquota = new javax.swing.JTextField();
        lblAliquota = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblImposto = new javax.swing.JLabel();
        lblValorBasico = new javax.swing.JLabel();
        rbUtilitario = new javax.swing.JRadioButton();
        lblCategoria = new javax.swing.JLabel();
        txtImposto = new javax.swing.JTextField();
        lblValorTotal = new javax.swing.JLabel();
        rbPasseio = new javax.swing.JRadioButton();
        lblMotorizacao = new javax.swing.JLabel();
        txtValorBasico = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtPlaca = new javax.swing.JFormattedTextField();
        btCalcular = new javax.swing.JButton();
        btCalcular.setIcon(new ImageIcon(CadCarro.class.getResource("/br/cesjf/lpiu/icons/validar.png")));
        btnAlterar = new javax.swing.JButton();
        btnAlterar.setIcon(new ImageIcon(CadCarro.class.getResource("/br/cesjf/lpiu/icons/editar.png")));
        btnExcluir = new javax.swing.JButton();
        btnExcluir.setIcon(new ImageIcon(CadCarro.class.getResource("/br/cesjf/lpiu/icons/excluir.png")));
        txtData = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCarro = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Veículos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(600, 550));
        setMinimumSize(new java.awt.Dimension(600, 550));
        setName("frameCadCarro"); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 550));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btLimpar.setText("Limpar");
        btLimpar.setIconTextGap(2);
        btLimpar.setMargin(new java.awt.Insets(1, 8, 1, 8));
        btLimpar.setMaximumSize(new java.awt.Dimension(130, 35));
        btLimpar.setMinimumSize(new java.awt.Dimension(130, 35));
        btLimpar.setPreferredSize(new java.awt.Dimension(130, 35));
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 110, -1));

        btTipoCarro.add(rbCarga);
        rbCarga.setText("Carga");
        getContentPane().add(rbCarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, -1, -1));

        lblPlaca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlaca.setText("Placa");
        getContentPane().add(lblPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 150, 20));

        txtValorTotal.setEnabled(false);
        txtValorTotal.setMaximumSize(new java.awt.Dimension(120, 25));
        txtValorTotal.setMinimumSize(new java.awt.Dimension(120, 25));
        txtValorTotal.setPreferredSize(new java.awt.Dimension(120, 25));
        getContentPane().add(txtValorTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 140, -1));

        lblDadosAutomovel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDadosAutomovel.setText("Dados do Automovel");
        getContentPane().add(lblDadosAutomovel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 570, -1));

        comboMotorizacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1.0", "1.3", "1.4", "1.6", "1.8", "2.0" }));
        comboMotorizacao.setSelectedIndex(-1);
        comboMotorizacao.setToolTipText("");
        comboMotorizacao.setMaximumSize(new java.awt.Dimension(120, 25));
        comboMotorizacao.setMinimumSize(new java.awt.Dimension(120, 25));
        comboMotorizacao.setPreferredSize(new java.awt.Dimension(120, 25));
        getContentPane().add(comboMotorizacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        jbAdd.setText("Adicionar");
        jbAdd.setEnabled(false);
        jbAdd.setIconTextGap(2);
        jbAdd.setMargin(new java.awt.Insets(1, 8, 1, 8));
        jbAdd.setMaximumSize(new java.awt.Dimension(120, 35));
        jbAdd.setMinimumSize(new java.awt.Dimension(120, 35));
        jbAdd.setPreferredSize(new java.awt.Dimension(120, 35));
        jbAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddActionPerformed(evt);
            }
        });
        getContentPane().add(jbAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        lblAno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAno.setText("Ano de Fabricação:");
        getContentPane().add(lblAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 140, -1));

        txtAliquota.setMaximumSize(new java.awt.Dimension(120, 25));
        txtAliquota.setMinimumSize(new java.awt.Dimension(120, 25));
        txtAliquota.setPreferredSize(new java.awt.Dimension(120, 25));
        getContentPane().add(txtAliquota, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 140, -1));

        lblAliquota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAliquota.setText("Aliquota de imposto");
        getContentPane().add(lblAliquota, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 140, -1));

        lblModelo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModelo.setText("Modelo");
        getContentPane().add(lblModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 330, 20));

        lblImposto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImposto.setText("Valor do Imposto");
        getContentPane().add(lblImposto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 150, -1));

        lblValorBasico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValorBasico.setText("Valor Basico");
        getContentPane().add(lblValorBasico, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 150, -1));

        btTipoCarro.add(rbUtilitario);
        rbUtilitario.setText("Utilitario");
        getContentPane().add(rbUtilitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));

        lblCategoria.setText("Categoria");
        getContentPane().add(lblCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        txtImposto.setEnabled(false);
        txtImposto.setMaximumSize(new java.awt.Dimension(120, 25));
        txtImposto.setMinimumSize(new java.awt.Dimension(120, 25));
        txtImposto.setPreferredSize(new java.awt.Dimension(120, 25));
        getContentPane().add(txtImposto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 150, -1));

        lblValorTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValorTotal.setText("Valor Total");
        getContentPane().add(lblValorTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 140, -1));

        btTipoCarro.add(rbPasseio);
        rbPasseio.setText("Passeio");
        getContentPane().add(rbPasseio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        lblMotorizacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMotorizacao.setText("Motorizacao");
        getContentPane().add(lblMotorizacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 120, -1));

        txtValorBasico.setMaximumSize(new java.awt.Dimension(120, 25));
        txtValorBasico.setMinimumSize(new java.awt.Dimension(120, 25));
        txtValorBasico.setPreferredSize(new java.awt.Dimension(120, 25));
        getContentPane().add(txtValorBasico, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 150, -1));

        txtModelo.setMaximumSize(new java.awt.Dimension(210, 25));
        txtModelo.setMinimumSize(new java.awt.Dimension(210, 25));
        txtModelo.setPreferredSize(new java.awt.Dimension(210, 25));
        getContentPane().add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 330, -1));

        try {
            txtPlaca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("???-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtPlaca.setMaximumSize(new java.awt.Dimension(120, 25));
        txtPlaca.setMinimumSize(new java.awt.Dimension(120, 25));
        txtPlaca.setPreferredSize(new java.awt.Dimension(120, 25));
        getContentPane().add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 150, -1));

        btCalcular.setText("Calcular");
        btCalcular.setIconTextGap(0);
        btCalcular.setMargin(new java.awt.Insets(1, 8, 1, 8));
        btCalcular.setMaximumSize(new java.awt.Dimension(110, 35));
        btCalcular.setMinimumSize(new java.awt.Dimension(110, 35));
        btCalcular.setPreferredSize(new java.awt.Dimension(110, 35));
        btCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.setIconTextGap(2);
        btnAlterar.setMargin(new java.awt.Insets(1, 8, 1, 8));
        btnAlterar.setMaximumSize(new java.awt.Dimension(100, 35));
        btnAlterar.setMinimumSize(new java.awt.Dimension(100, 35));
        btnAlterar.setPreferredSize(new java.awt.Dimension(100, 35));
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, -1, -1));

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.setIconTextGap(2);
        btnExcluir.setMargin(new java.awt.Insets(1, 8, 1, 8));
        btnExcluir.setMaximumSize(new java.awt.Dimension(100, 35));
        btnExcluir.setMinimumSize(new java.awt.Dimension(100, 35));
        btnExcluir.setPreferredSize(new java.awt.Dimension(100, 35));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, -1, -1));

        txtData.setMaximumSize(new java.awt.Dimension(120, 25));
        txtData.setMinimumSize(new java.awt.Dimension(120, 25));
        txtData.setPreferredSize(new java.awt.Dimension(120, 25));
        getContentPane().add(txtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 140, -1));

        jTableCarro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Modelo", "Fabricação", "Motorização", "Valor Basico", "Categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCarro.setColumnSelectionAllowed(true);
        jTableCarro.getTableHeader().setReorderingAllowed(false);
        jTableCarro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCarroMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableCarro);
        jTableCarro.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 560, 130));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Principal princ = new Principal();
        princ.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void btCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcularActionPerformed

        Double valorBasico = Double.parseDouble(txtValorBasico.getText());
        Double aliquota = Double.parseDouble(txtAliquota.getText());

        Double imposto = auto.calcularImposto(valorBasico, aliquota);
        txtImposto.setText(imposto.toString());

        txtValorTotal.setText(String.valueOf(auto.calcularValorTotal(valorBasico, imposto)));

        jbAdd.setEnabled(true);

    }//GEN-LAST:event_btCalcularActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void jbAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddActionPerformed

        auto.setPlaca(txtPlaca.getText());
        auto.setModelo(txtModelo.getText());
        auto.setDataDeFabricacao(txtData.getText());
        auto.setValorBasico(Double.parseDouble(txtValorBasico.getText()));
        auto.setMotorizacao( (String) comboMotorizacao.getSelectedItem());
        
        rbCarga.setActionCommand("Carga");
        rbPasseio.setActionCommand("Passeio");
        rbUtilitario.setActionCommand("Utilitario");
        
        auto.setCategoria(btTipoCarro.getSelection().getActionCommand());
        
//        String aliquota = txtAliquota.getText();
//        String imposto = txtImposto.getText();
//        String ValorTotal = txtValorTotal.getText();
        
        try {
            arqout.Adicionar(auto);
        } catch (IOException ex) {
            Logger.getLogger(CadCarro.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JOptionPane.showMessageDialog(null, "Carro Inserido com Sucesso!");
        
        limpar();
        jbAdd.setEnabled(false);
        
        int cont = 1;

        List<Automovel> listacar = new ArrayList<Automovel>();

        listacar = arqin.getTodosCarros();
        DefaultTableModel modelocarro = (DefaultTableModel) jTableCarro.getModel();

        for (int i = jTableCarro.getRowCount() - 1; i >= 0; --i) {
            modelocarro.removeRow(i);
        }

        for (int i = 0; i < listacar.size(); i++) {
            modelocarro.addRow(listacar.get(i).getcarro());
            cont++;
        }
    }//GEN-LAST:event_jbAddActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jTableCarro.getModel();
        List<Automovel> list = new ArrayList<Automovel>();
        ArrayList<Automovel> nova_list = new ArrayList<Automovel>();
        
        linha = jTableCarro.getSelectedRow();
        Object valor = modelo.getValueAt(linha, 0);
        list = arqin.getTodosCarros();
        
        for (int i = 0; i < list.size(); i++) {
            if (!(list.get(i).getPlaca().equals(valor))) {
                nova_list.add(list.get(i));
            }
        }
        try {
            arqout.recadastrar_todos(nova_list);
        } catch (IOException ex) {
            Logger.getLogger(CadCarro.class.getName()).log(Level.SEVERE, null, ex);
        }

        modelo.removeRow(linha);
        JOptionPane.showMessageDialog(null, "Registro apagada com sucesso");
        
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        ArrayList<Automovel> listauto = new ArrayList<Automovel>();
        listauto = (ArrayList<Automovel>) arqin.getTodosCarros();

        rbCarga.setActionCommand("Carga");
        rbPasseio.setActionCommand("Passeio");
        rbUtilitario.setActionCommand("Utilitario");
        
        listauto.get(linha).setPlaca(txtPlaca.getText());
        listauto.get(linha).setModelo(txtModelo.getText());
        listauto.get(linha).setDataDeFabricacao(txtData.getText());
        listauto.get(linha).setValorBasico(Double.parseDouble(txtValorBasico.getText()));
        listauto.get(linha).setMotorizacao( (String) comboMotorizacao.getSelectedItem());
        listauto.get(linha).setCategoria(btTipoCarro.getSelection().getActionCommand());
                
        try {
            arqout.recadastrar_todos(listauto);
        } catch (IOException ex){
            Logger.getLogger(CadCarro.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JOptionPane.showMessageDialog(null, "Registro Alterado com Sucesso!");
        limpar();
        
        DefaultTableModel modelo = (DefaultTableModel) jTableCarro.getModel();
        
        if(jTableCarro.getRowCount() > 0){
            for (int i=jTableCarro.getRowCount() - 1; i>=0; i--){
                modelo.removeRow(i);
            }
        }
        
        List<Automovel> listauto2 = new ArrayList<Automovel>();
        listauto2 = arqin.getTodosCarros();
        
        for (int i=0; i < listauto2.size(); i++){
            modelo.addRow(listauto2.get(i).getcarro());
        }
        
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        int cont = 1;

        List<Automovel> listacar = new ArrayList<Automovel>();

        listacar = arqin.getTodosCarros();
        DefaultTableModel modelocarro = (DefaultTableModel) jTableCarro.getModel();

        for (int i = jTableCarro.getRowCount() - 1; i >= 0; --i) {
            modelocarro.removeRow(i);
        }

        for (int i = 0; i < listacar.size(); i++) {
            modelocarro.addRow(listacar.get(i).getcarro());
            cont++;
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void jTableCarroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCarroMouseClicked
        btnAlterar.setEnabled(true);
        btnExcluir.setEnabled(true);
        linha = jTableCarro.getSelectedRow();

        txtPlaca.setText(jTableCarro.getValueAt(linha, 0).toString());
        txtModelo.setText(jTableCarro.getValueAt(linha, 1).toString());
        txtData.setText(jTableCarro.getValueAt(linha, 2).toString());
        String motor = jTableCarro.getValueAt(linha, 3).toString();
            if (motor.equals("1.0")){
                comboMotorizacao.setSelectedIndex(0);
            }else if (motor.equals("1.3")){
                comboMotorizacao.setSelectedIndex(1);
            }else if (motor.equals("1.4")){
                comboMotorizacao.setSelectedIndex(2);
            }else if (motor.equals("1.6")){
                comboMotorizacao.setSelectedIndex(3);
            }else if (motor.equals("1.8")){
                comboMotorizacao.setSelectedIndex(4);
            }else if (motor.equals("2.0")){
                comboMotorizacao.setSelectedIndex(5);
            }
        txtValorBasico.setText(jTableCarro.getValueAt(linha, 4).toString());
        String tipo = jTableCarro.getValueAt(linha, 5).toString();
            if (tipo.equals("Carga")) {
                rbCarga.setSelected(true);
            } else if (tipo.equals("Passeio")) {
                rbPasseio.setSelected(true);
            } else {
                rbUtilitario.setSelected(true);
            }
    }//GEN-LAST:event_jTableCarroMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadCarro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCalcular;
    private javax.swing.JButton btLimpar;
    private javax.swing.ButtonGroup btTipoCarro;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JComboBox<String> comboMotorizacao;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCarro;
    private javax.swing.JButton jbAdd;
    private javax.swing.JLabel lblAliquota;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblDadosAutomovel;
    private javax.swing.JLabel lblImposto;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblMotorizacao;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblValorBasico;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JRadioButton rbCarga;
    private javax.swing.JRadioButton rbPasseio;
    private javax.swing.JRadioButton rbUtilitario;
    private javax.swing.JTextField txtAliquota;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtImposto;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JFormattedTextField txtPlaca;
    private javax.swing.JTextField txtValorBasico;
    private javax.swing.JTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables
}
