/**
 * @author Laura
 */

package br.cesjf.lpiu.interfaces;

import br.cesjf.lpiu.arquivos.ArquivoInPessoa;
import br.cesjf.lpiu.arquivos.ArquivoOutPessoa;
import br.cesjf.lpiu.modelo.Pessoa;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

public class CadPessoas extends javax.swing.JFrame {

    private ArquivoInPessoa arqin = new ArquivoInPessoa();
    int linha; //pega a linha que o usuário clicou na tabela - para retornar dados ao formulário
    private ArquivoOutPessoa arqout = new ArquivoOutPessoa();
    
    /**
     * Creates new form CadastroPessoas
     */
    public CadPessoas() {
    	setIconImage(Toolkit.getDefaultToolkit().getImage(CadPessoas.class.getResource("/br/cesjf/lpiu/icons/logo2.png")));
        initComponents();
        pess = new Pessoa();
        try {
            arqout.abrir();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CadPessoas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(CadPessoas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public Pessoa pess = null;
    
    public void limpar() {
        txtCpf.setText("");
        txtNome.setText("");
        txtNascimento.setText("");
        txtCnh.setText("");
        txtCep.setText("");
        txtEndereco.setText("");
        txtNumero.setText("");
        txtComplemento.setText("");
        txtBairro.setText("");
        txtCidade.setText("");
        cboEstado.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCpf = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblNascimento = new javax.swing.JLabel();
        lblCnh = new javax.swing.JLabel();
        txtCnh = new javax.swing.JTextField();
        lblCep = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblComplemento = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        cboEstado = new javax.swing.JComboBox<>();
        btnCadastrar = new javax.swing.JButton();
        btnCadastrar.setIcon(new ImageIcon(CadPessoas.class.getResource("/br/cesjf/lpiu/icons/add.png")));
        btnExcluir = new javax.swing.JButton();
        btnExcluir.setIcon(new ImageIcon(CadPessoas.class.getResource("/br/cesjf/lpiu/icons/excluir.png")));
        btnLimpar = new javax.swing.JButton();
        btnLimpar.setIcon(new ImageIcon(CadPessoas.class.getResource("/br/cesjf/lpiu/icons/limpar.png")));
        btnVisualizar = new javax.swing.JButton();
        txtCpf = new javax.swing.JFormattedTextField();
        txtCep = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        btnAlterar = new javax.swing.JButton();
        btnAlterar.setIcon(new ImageIcon(CadPessoas.class.getResource("/br/cesjf/lpiu/icons/editar.png")));
        txtNascimento = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTablePessoas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblCpf.setText("CPF: ");

        lblNome.setText("Nome: ");

        txtNome.setMaximumSize(new java.awt.Dimension(422, 25));
        txtNome.setMinimumSize(new java.awt.Dimension(422, 25));
        txtNome.setPreferredSize(new java.awt.Dimension(422, 25));

        lblNascimento.setText("Data de Nascimento: ");

        lblCnh.setText("CNH: ");

        txtCnh.setMaximumSize(new java.awt.Dimension(180, 25));
        txtCnh.setMinimumSize(new java.awt.Dimension(180, 25));
        txtCnh.setPreferredSize(new java.awt.Dimension(180, 25));

        lblCep.setText("CEP: ");

        lblEndereco.setText("Endereço: ");

        txtEndereco.setMaximumSize(new java.awt.Dimension(150, 25));
        txtEndereco.setMinimumSize(new java.awt.Dimension(150, 25));
        txtEndereco.setPreferredSize(new java.awt.Dimension(180, 25));

        lblNumero.setText("Número: ");

        txtNumero.setMaximumSize(new java.awt.Dimension(150, 25));
        txtNumero.setMinimumSize(new java.awt.Dimension(150, 25));
        txtNumero.setPreferredSize(new java.awt.Dimension(150, 25));

        lblComplemento.setText("Complemento: ");

        txtComplemento.setMaximumSize(new java.awt.Dimension(150, 25));
        txtComplemento.setMinimumSize(new java.awt.Dimension(150, 25));
        txtComplemento.setPreferredSize(new java.awt.Dimension(180, 25));

        lblBairro.setText("Bairro: ");

        txtBairro.setMaximumSize(new java.awt.Dimension(150, 25));
        txtBairro.setMinimumSize(new java.awt.Dimension(150, 25));
        txtBairro.setPreferredSize(new java.awt.Dimension(150, 25));

        lblCidade.setText("Cidade: ");

        txtCidade.setMaximumSize(new java.awt.Dimension(150, 25));
        txtCidade.setMinimumSize(new java.awt.Dimension(150, 25));
        txtCidade.setPreferredSize(new java.awt.Dimension(180, 25));

        lblEstado.setText("Estado: ");

        cboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cboEstado.setSelectedIndex(-1);
        cboEstado.setMaximumSize(new java.awt.Dimension(70, 25));
        cboEstado.setMinimumSize(new java.awt.Dimension(70, 25));
        cboEstado.setPreferredSize(new java.awt.Dimension(70, 25));

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setMaximumSize(new java.awt.Dimension(110, 35));
        btnCadastrar.setMinimumSize(new java.awt.Dimension(110, 35));
        btnCadastrar.setPreferredSize(new java.awt.Dimension(110, 35));
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.setMaximumSize(new java.awt.Dimension(110, 35));
        btnExcluir.setMinimumSize(new java.awt.Dimension(110, 35));
        btnExcluir.setPreferredSize(new java.awt.Dimension(110, 35));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.setMaximumSize(new java.awt.Dimension(110, 35));
        btnLimpar.setMinimumSize(new java.awt.Dimension(110, 35));
        btnLimpar.setPreferredSize(new java.awt.Dimension(110, 35));
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnVisualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/cesjf/lpiu/icons/visualizar.png"))); // NOI18N
        btnVisualizar.setMaximumSize(new java.awt.Dimension(25, 25));
        btnVisualizar.setMinimumSize(new java.awt.Dimension(25, 25));
        btnVisualizar.setPreferredSize(new java.awt.Dimension(25, 25));
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.setMaximumSize(new java.awt.Dimension(200, 25));
        txtCpf.setMinimumSize(new java.awt.Dimension(200, 25));
        txtCpf.setPreferredSize(new java.awt.Dimension(200, 25));

        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCep.setMaximumSize(new java.awt.Dimension(200, 25));
        txtCep.setMinimumSize(new java.awt.Dimension(200, 25));
        txtCep.setPreferredSize(new java.awt.Dimension(200, 25));

        jLabel1.setText("Visualizar todos os dados detalhados: ");

        btnAlterar.setText("Alterar");
        btnAlterar.setMaximumSize(new java.awt.Dimension(110, 35));
        btnAlterar.setMinimumSize(new java.awt.Dimension(110, 35));
        btnAlterar.setPreferredSize(new java.awt.Dimension(110, 35));
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        try {
            txtNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNascimento.setMaximumSize(new java.awt.Dimension(150, 25));
        txtNascimento.setMinimumSize(new java.awt.Dimension(150, 25));
        txtNascimento.setPreferredSize(new java.awt.Dimension(150, 25));

        JTablePessoas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CPF", "Nome", "Nascimento", "CNH", "CEP", "Endereço", "Número", "Complemento", "Bairro", "Cidade", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTablePessoas.getTableHeader().setReorderingAllowed(false);
        JTablePessoas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTablePessoasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(JTablePessoas);
        if (JTablePessoas.getColumnModel().getColumnCount() > 0) {
            JTablePessoas.getColumnModel().getColumn(0).setResizable(false);
            JTablePessoas.getColumnModel().getColumn(1).setResizable(false);
            JTablePessoas.getColumnModel().getColumn(2).setResizable(false);
            JTablePessoas.getColumnModel().getColumn(2).setPreferredWidth(0);
            JTablePessoas.getColumnModel().getColumn(3).setResizable(false);
            JTablePessoas.getColumnModel().getColumn(3).setPreferredWidth(0);
            JTablePessoas.getColumnModel().getColumn(4).setResizable(false);
            JTablePessoas.getColumnModel().getColumn(4).setPreferredWidth(0);
            JTablePessoas.getColumnModel().getColumn(5).setResizable(false);
            JTablePessoas.getColumnModel().getColumn(6).setResizable(false);
            JTablePessoas.getColumnModel().getColumn(7).setResizable(false);
            JTablePessoas.getColumnModel().getColumn(7).setPreferredWidth(0);
            JTablePessoas.getColumnModel().getColumn(8).setResizable(false);
            JTablePessoas.getColumnModel().getColumn(9).setResizable(false);
            JTablePessoas.getColumnModel().getColumn(10).setResizable(false);
            JTablePessoas.getColumnModel().getColumn(10).setPreferredWidth(0);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNascimento)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(15, 15, 15)
                                        .addComponent(lblCnh)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblComplemento)
                                                    .addComponent(lblEndereco))
                                                .addGap(20, 20, 20)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblCidade)
                                                .addGap(52, 52, 52)
                                                .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(lblNumero)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(lblEstado)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(lblBairro)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNome)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(4, 4, 4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(lblCep)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(lblCpf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpf)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNascimento)
                    .addComponent(lblCnh)
                    .addComponent(txtCnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCep)
                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEndereco)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumero)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBairro)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblComplemento))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCidade)
                    .addComponent(lblEstado)
                    .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnVisualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) JTablePessoas.getModel();
        List<Pessoa> list = new ArrayList<Pessoa>();
        ArrayList<Pessoa> nova_list = new ArrayList<Pessoa>();
        
        linha = JTablePessoas.getSelectedRow();
        Object valor = modelo.getValueAt(linha, 0);
        list = arqin.getTodasPessoas();
        
        for (int i = 0; i < list.size(); i++) {
            if (!(list.get(i).getCpf().equals(valor))) {
                nova_list.add(list.get(i));
            }
        }
        try {
            arqout.recadastrar_todos(nova_list);
        } catch (IOException ex) {
            Logger.getLogger(CadPessoas.class.getName()).log(Level.SEVERE, null, ex);
        }

        modelo.removeRow(linha);
        JOptionPane.showMessageDialog(null, "Registro apagada com sucesso");
        
        btnExcluir.setEnabled(false);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        
        pess.setCpf(txtCpf.getText());
        pess.setNome(txtNome.getText());
        pess.setData(txtNascimento.getText());
        pess.setCnh(txtCnh.getText());
        pess.setCep(txtCep.getText());
        pess.setEndereco(txtEndereco.getText());
        pess.setNumero(txtNumero.getText());
        pess.setComplemento(txtComplemento.getText());
        pess.setBairro(txtBairro.getText());
        pess.setCidade(txtCidade.getText());
        pess.setEstado((String)cboEstado.getSelectedItem());
        
        try {
            arqout.Adicionar(pess);
        } catch (IOException ex) {
            Logger.getLogger(CadPessoas.class.getName()).log(Level.SEVERE, null, ex);
            System.out.print("ERRO AQUI");
        }
        
        JOptionPane.showMessageDialog(null, "Cadastro Inserido com Sucesso!");
        
        limpar();
        btnCadastrar.setEnabled(false);
        
        int cont = 1;

        List<Pessoa> listaP = new ArrayList<Pessoa>();

        listaP = arqin.getTodasPessoas();
        DefaultTableModel modelopessoa = (DefaultTableModel) JTablePessoas.getModel();

        for (int i = JTablePessoas.getRowCount() - 1; i >= 0; --i) {
            modelopessoa.removeRow(i);
        }

        for (int i = 0; i < listaP.size(); i++) {
            modelopessoa.addRow(listaP.get(i).getpessoa());
            cont++;
        }
        
//        ListaPessoas listar = new ListaPessoas();
//        listar.setVisible(true);
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed
        ListaPessoas listarP = new ListaPessoas();
        listarP.setVisible(true);
    }//GEN-LAST:event_btnVisualizarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Principal princ = new Principal();
        princ.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        ArrayList<Pessoa> listaP = new ArrayList<Pessoa>();
        listaP = (ArrayList<Pessoa>) arqin.getTodasPessoas();
        
        listaP.get(linha).setCpf(txtCpf.getText());
        listaP.get(linha).setNome(txtNome.getText());
        listaP.get(linha).setData(txtNascimento.getText());
        listaP.get(linha).setCnh(txtCnh.getText());
        listaP.get(linha).setCep(txtCep.getText());
        listaP.get(linha).setEndereco(txtEndereco.getText());
        listaP.get(linha).setNumero(txtNumero.getText());
        listaP.get(linha).setComplemento(txtCnh.getText());
        listaP.get(linha).setBairro(txtBairro.getText());
        listaP.get(linha).setCidade(txtCidade.getText());
        listaP.get(linha).setEstado( (String) cboEstado.getSelectedItem());
                
        try {
            arqout.recadastrar_todos(listaP);
        } catch (IOException ex){
            Logger.getLogger(CadPessoas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JOptionPane.showMessageDialog(null, "Registro Alterado com Sucesso!");
        limpar();
        
        DefaultTableModel modelo = (DefaultTableModel) JTablePessoas.getModel();
        
        if(JTablePessoas.getRowCount() > 0){
            for (int i=JTablePessoas.getRowCount() - 1; i>=0; i--){
                modelo.removeRow(i);
            }
        }
        
        List<Pessoa> listap2 = new ArrayList<Pessoa>();
        listap2 = arqin.getTodasPessoas();
        
        for (int i=0; i < listap2.size(); i++){
            modelo.addRow(listap2.get(i).getpessoa());
        }
        
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        int cont = 1;

        List<Pessoa> listaPessoa = new ArrayList<Pessoa>();

        listaPessoa = arqin.getTodasPessoas();
        DefaultTableModel modeloPessoa = (DefaultTableModel) JTablePessoas.getModel();

        for (int i = JTablePessoas.getRowCount() - 1; i >= 0; --i) {
        	modeloPessoa.removeRow(i);
        }

        for (int i = 0; i < listaPessoa.size(); i++) {
        	modeloPessoa.addRow(listaPessoa.get(i).getpessoa());
            cont++;
        }
    }//GEN-LAST:event_formWindowOpened

    private void JTablePessoasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTablePessoasMouseClicked
        
        btnAlterar.setEnabled(true);
        btnExcluir.setEnabled(true);
        linha = JTablePessoas.getSelectedRow();

        txtCpf.setText(JTablePessoas.getValueAt(linha, 0).toString());
        txtNome.setText(JTablePessoas.getValueAt(linha, 1).toString());
        txtNascimento.setText(JTablePessoas.getValueAt(linha, 2).toString());
        txtCnh.setText(JTablePessoas.getValueAt(linha, 3).toString());
        txtCep.setText(JTablePessoas.getValueAt(linha, 4).toString());
        txtEndereco.setText(JTablePessoas.getValueAt(linha, 5).toString());
        txtNumero.setText(JTablePessoas.getValueAt(linha, 6).toString());
        txtComplemento.setText(JTablePessoas.getValueAt(linha, 7).toString());
        txtBairro.setText(JTablePessoas.getValueAt(linha, 8).toString());
        txtCidade.setText(JTablePessoas.getValueAt(linha, 9).toString());
        
        
        String estado = JTablePessoas.getValueAt(linha, 10).toString();
        
        String [] vetorEstados = {"AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", 
            "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", 
            "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO"};
        for (int i = 0; i < vetorEstados.length; i++){
            if (estado.equals(vetorEstados[i])){
                cboEstado.setSelectedIndex(i);
            }
        }
    }//GEN-LAST:event_JTablePessoasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadPessoas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTablePessoas;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JComboBox<String> cboEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCnh;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblNascimento;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCnh;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JFormattedTextField txtNascimento;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
