/**
 * @author laura
 */

package br.cesjf.lpiu.interfaces;

import br.cesjf.lpiu.modelo.Usuario;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.awt.Toolkit;
import javax.swing.JLabel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

public class Login extends javax.swing.JFrame {
   
    public Login() {
    	setIconImage(Toolkit.getDefaultToolkit().getImage(Login.class.getResource("/br/cesjf/lpiu/icons/logo2.png")));
    	//setIconImage(Toolkit.getDefaultToolkit().getImage(Login.class.getResource("/br/cesjf/lpiu/icons/logo2.png")));
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbUsuario = new javax.swing.JLabel();
        lbUsuario.setIcon(null);
        lbSenha = new javax.swing.JLabel();
        lbSenha.setIcon(null);
        txtUsuario = new javax.swing.JTextField();
        btLogar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btLimpar.setIcon(new ImageIcon(Login.class.getResource("/br/cesjf/lpiu/icons/limpar.png")));
        txtSenha = new javax.swing.JPasswordField();
        jbSair = new javax.swing.JButton();
        jbSair.setIcon(new ImageIcon(Login.class.getResource("/br/cesjf/lpiu/icons/sair.png")));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login do Sistema");
        setResizable(false);

        lbUsuario.setText("Usuário:");

        lbSenha.setText("Senha:");

        txtUsuario.setText("admin");
        txtUsuario.setMaximumSize(new java.awt.Dimension(210, 25));
        txtUsuario.setMinimumSize(new java.awt.Dimension(210, 25));
        txtUsuario.setPreferredSize(new java.awt.Dimension(210, 25));
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        btLogar.setIcon(new ImageIcon(Login.class.getResource("/br/cesjf/lpiu/icons/validar.png"))); // NOI18N
        btLogar.setText("Acessar");
        btLogar.setMaximumSize(new java.awt.Dimension(120, 35));
        btLogar.setMinimumSize(new java.awt.Dimension(120, 35));
        btLogar.setPreferredSize(new java.awt.Dimension(120, 35));
        btLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogarActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.setMaximumSize(new java.awt.Dimension(120, 35));
        btLimpar.setMinimumSize(new java.awt.Dimension(120, 35));
        btLimpar.setPreferredSize(new java.awt.Dimension(120, 35));
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        txtSenha.setText("1234567");
        txtSenha.setMaximumSize(new java.awt.Dimension(210, 25));
        txtSenha.setMinimumSize(new java.awt.Dimension(210, 25));
        txtSenha.setPreferredSize(new java.awt.Dimension(210, 25));

        jbSair.setText("Sair");
        jbSair.setMaximumSize(new java.awt.Dimension(120, 35));
        jbSair.setMinimumSize(new java.awt.Dimension(120, 35));
        jbSair.setPreferredSize(new java.awt.Dimension(120, 35));
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });
        
        JLabel label = new JLabel("");
        label.setIcon(new ImageIcon(Login.class.getResource("/br/cesjf/lpiu/icons/pessoa.png")));
        
        JLabel label_1 = new JLabel("");
        label_1.setIcon(new ImageIcon(Login.class.getResource("/br/cesjf/lpiu/icons/senha.png")));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(15, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(btLogar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(btLimpar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jbSair, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(label)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(lbUsuario))
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(label_1)
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addComponent(lbSenha)))
        					.addGap(18)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(txtSenha, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(txtUsuario, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
        			.addGap(15))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(30)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createParallelGroup(Alignment.LEADING)
        					.addComponent(lbUsuario, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
        					.addComponent(txtUsuario, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addComponent(label))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(txtSenha, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addComponent(lbSenha))
        				.addComponent(label_1))
        			.addGap(30)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btLogar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btLimpar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jbSair, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(20))
        );
        getContentPane().setLayout(layout);

        getAccessibleContext().setAccessibleName("Sistema de Gestão de Veículos");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        txtUsuario.setText("");
        txtSenha.setText("");
        txtUsuario.requestFocus();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogarActionPerformed

        Usuario usuario = new Usuario();

        String nomeUsuario = txtUsuario.getText();
        String senhaUsuario = txtSenha.getText();

        if (usuario.validarLogin(nomeUsuario)) {
            if (usuario.validarSenha(senhaUsuario)) {
                if (usuario.autenticar(nomeUsuario, senhaUsuario)) {
                    Principal main = new Principal();
                    main.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Usuário Não Autenticado", "Erro", JOptionPane.ERROR_MESSAGE);
                   }
            } else {
                JOptionPane.showMessageDialog(null, "Senha Falhou", "Erro", JOptionPane.ERROR_MESSAGE);
                }

        } else {
            JOptionPane.showMessageDialog(null, "Login Falhou", "Erro", JOptionPane.ERROR_MESSAGE);
            }

    }//GEN-LAST:event_btLogarActionPerformed
    
    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        System.exit(0);        
    }//GEN-LAST:event_jbSairActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btLogar;
    private javax.swing.JButton jbSair;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
}
