/**
 * @author laura
 */

package br.cesjf.lpiu.interfaces;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.GroupLayout.Alignment;
import java.awt.Dimension;
import javax.swing.GroupLayout;
import java.awt.Component;
import javax.swing.SwingConstants;

public class Principal extends javax.swing.JFrame {

    public Principal() {
    	setPreferredSize(new Dimension(400, 300));
    	setIconImage(Toolkit.getDefaultToolkit().getImage(Principal.class.getResource("/br/cesjf/lpiu/icons/logo2.png")));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuCadCarro = new javax.swing.JMenuItem();
        menuCadCarro.setIcon(new ImageIcon(Principal.class.getResource("/br/cesjf/lpiu/icons/carro.png")));
        menuCadPessoas = new javax.swing.JMenuItem();
        menuCadPessoas.setIcon(new ImageIcon(Principal.class.getResource("/br/cesjf/lpiu/icons/pessoa.png")));
        menuAssociacoes = new javax.swing.JMenuItem();
        menuAssociacoes.setIcon(new ImageIcon(Principal.class.getResource("/br/cesjf/lpiu/icons/link.png")));
        jMenuAjuda = new javax.swing.JMenu();
        jMSobre = new javax.swing.JMenuItem();
        jMSobre.setIcon(new ImageIcon(Principal.class.getResource("/br/cesjf/lpiu/icons/info.png")));

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestão de Veículos");
        setIconImages(null);
        setResizable(false);

        jMenu1.setText("Controle");

        menuCadCarro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        menuCadCarro.setText("Cadastro de Carros");
        menuCadCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadCarroActionPerformed(evt);
            }
        });
        jMenu1.add(menuCadCarro);

        menuCadPessoas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        menuCadPessoas.setText("Cadastro de Pessoas");
        menuCadPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadPessoasActionPerformed(evt);
            }
        });
        jMenu1.add(menuCadPessoas);

        menuAssociacoes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        menuAssociacoes.setText("Associações");
        menuAssociacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAssociacoesActionPerformed(evt);
            }
        });
        jMenu1.add(menuAssociacoes);

        jMenuBar1.add(jMenu1);

        jMenuAjuda.setText("Ajuda");

        jMSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMSobre.setText("Sobre");
        jMSobre.setMaximumSize(new java.awt.Dimension(100, 40));
        jMSobre.setMinimumSize(new java.awt.Dimension(100, 40));
        jMSobre.setPreferredSize(new java.awt.Dimension(100, 40));
        jMSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSobreActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMSobre);

        jMenuBar1.add(jMenuAjuda);

        setJMenuBar(jMenuBar1);
        
        lblNewLabel = new JLabel("");
        lblNewLabel.setHorizontalAlignment(SwingConstants.CENTER);
        lblNewLabel.setHorizontalTextPosition(SwingConstants.CENTER);
        lblNewLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
        lblNewLabel.setIcon(new ImageIcon(Principal.class.getResource("/br/cesjf/lpiu/icons/carGarage.png")));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 250, Short.MAX_VALUE)
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 250, Short.MAX_VALUE)
        			.addGap(0))
        );
        getContentPane().setLayout(layout);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSobreActionPerformed
        LocalDateTime ldt = LocalDateTime.now();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd' do 'M' de 'yyyy' - 'HH':'mm' hrs'");
        JOptionPane.showMessageDialog(null, "Autora: \n Laura " + "\n Data e hora atual: \n"+ ldt.format(formato), null, JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMSobreActionPerformed

    private void menuCadCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadCarroActionPerformed
        CadCarro cadcar = new CadCarro();
        cadcar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuCadCarroActionPerformed

    private void menuCadPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadPessoasActionPerformed
        CadPessoas cadpess = new CadPessoas();
        cadpess.setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_menuCadPessoasActionPerformed

    private void menuAssociacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAssociacoesActionPerformed
        Associacoes asso = new Associacoes();
        asso.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuAssociacoesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMSobre;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem menuAssociacoes;
    private javax.swing.JMenuItem menuCadCarro;
    private javax.swing.JMenuItem menuCadPessoas;
    private JLabel lblNewLabel;
}
